### ISSUE TITLE
Update restana to 3.x

### ISSUE THREAD

**Issue by jkyberneees** [galtspace/geesome-core#39]
Hi @Jonybang  thanks for using `restana` on your project. 
I kindly suggest you to update `restana` to version  `3.x` for new features and fixes. 

Thanks and good luck on your awesome project!

**Comment by Jonybang** [comment]
@jkyberneees are there any breaking changes between these versions?

**Comment by jkyberneees** [comment]
No breaking changes when related to your code. 
`restana` 3.x "just" dropped `turbo-http` module support. 

In your case you are not using it, so is safe to upgrade.

**Comment by Jonybang** [comment]
@jkyberneees cool, thank you, i will upgrade
